[project]
name = "chromadbtest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=0.4.0,<1.0.0",
    "sentence-transformers>=2.2.0,<3.0.0",
    "numpy<2",
    "torch>=2.0.0,<2.3.0",
]
